---
label: Project
hide_body: false
fields:
- name: thumbnail
  type: file
  config:
    maxSize: 64
  label: Thumbnail
- name: title
  type: text
  config:
    required: true
  label: Title
- name: summary
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: Summary
- name: technologies
  type: tag_list
  default:
  - react
  label: Technologies
- name: projectLink
  type: text
  config:
    required: true
  label: Project Link
- name: galery
  type: image_gallery
  config: {}
  label: Galery
